### ISSUE TITLE
False claims

### ISSUE THREAD

**Issue by chmac** [trustroots-community/trustrots#4] opened 2024-01-31 16:51 UTC
> They also [revert recent code improvements](https://github.com/Trustroots/trustroots/commit/902e0261718fcb6bff7b4c9ca2774d5f872e6187).

These were not improvements at all. It was quite the opposite, which is why it was rolled back. It was one of the main reasons to clean up the GitHub permissions.

**Comment by mrkvon** [comment] 2024-01-31 20:05
@chmac Can you provide evidence or details to support your claim? The revert doesn't contain any reasoning.

Everybody can read my detailed description of the original PR in https://github.com/Trustroots/trustroots/pull/2650, and make up their mind whether this was an improvement or not.

**Comment by chmac** [comment] 2024-01-31 20:07
We're putting trustroots into maintenance mode. Adding new features is the opposite of what we're trying to do. Increasing the attack surface is not helpful, it is harmful.

**Comment by mrkvon** [comment] 2024-01-31 22:04
> Increasing the attack surface is not helpful, it is harmful.

Thanks for providing your reasoning.

[However](https://en.wikipedia.org/wiki/Security_through_obscurity#Criticism),

> "System security should not depend on the secrecy of the implementation or its components."

Yet still, security was reasonably taken into account (https://github.com/Trustroots/trustroots/pull/2650)

> - hide the API documentation behind feature flag { featureFlags: { apidocs: true } } in ./config/env/local.js
>   - by default it shows in development, but not in production

Furthermore, [Trustroots source code is publicly available](https://github.com/Trustroots/trustroots), so fundamentally it needs to rely on security by design. In this context, publishing API can actually increase security by encouraging transparency and peer review.

Closing this as resolved.

**Comment by chmac** [comment] 2024-01-31 22:05
You're free to publish that your opinion is it's an improvement. But by the decision of the site administrators, it was not, which is why it was reverted.

It seems like you're only really interested in telling your own side of the story.

**Comment by mrkvon** [comment] 2024-01-31 22:07
https://en.wikipedia.org/wiki/Ad_hominem

**Comment by chmac** [comment] 2024-01-31 22:21
Haha, good one!

The ad hominem fallacy would be if I were to say, "you're an idiot because you don't want to do x". Stating that you seem uninterested in publishing anything that doesn't fit your narrative is a behavioural observation, and phrases as such.

I am pointing out the apparent dichotomy between your published intentions and your behaviour.

Sadly it is what I have come to expect from you given my past observations of your behaviour. 😢

**Comment by mrkvon** [comment] 2024-01-31 22:29
> Typically this term refers to a rhetorical strategy where the speaker attacks the character, motive, or some other attribute of the person making an argument rather than attacking the substance of the argument itself. This avoids genuine debate by creating a personal attack as a diversion often using a totally irrelevant, but often highly charged attribute of the opponent's character or background. The most common form of this fallacy is "A" makes a claim of "fact," to which "B" asserts that "A" has a personal trait, quality or physical attribute that is repugnant thereby going entirely off-topic, and hence "B" concludes that "A" has their "fact" wrong -without ever addressing the point of the debate.

If you @chmac are willing to refocus on rational arguments, i'm happy to unlock this issue again.

**Comment by mrkvon** [comment] 2024-02-04 16:43
> https://en.wikipedia.org/wiki/Ad_hominem

Looking back, I realize that this response wasn't supportive of the conversation, and your response @chmac was indeed not an Ad hominem fallacy. My mistake.

Unlocking and reopening this.

**Comment by mrkvon** [comment] 2024-03-04 22:45
It looks like we can agree that the claim is somewhat subjective, but not objectively false.

On the other hand, Callum has already attempted to silence disagreeing voices, and suppressed my other contributions (see #9).

> It seems like you're only really interested in telling your own side of the story.

Of course I'm interested in telling my and other volunteers' side of the story. That's the whole point of this info. 😉 On the other hand I'm also happy to improve imperfections and inaccuracies, if they're well-founded.

Closing this as not planned. If anything new appears, happy to reopen.

**Closed by mrkvon** 2024-03-04 22:45 UTC
